--Type Kwon Do Two: electric typealoo
-- youre trying to till in terms which will fit
-- the type. The idea with these exercises ist aht you'll derive
-- the implementation from the type information.
